
export const EstadosDoBrasil = [
  { sigla: 'AC', nome: 'AC' },
  { sigla: 'AL', nome: 'AL' },
  { sigla: 'AM', nome: 'AM' },
  { sigla: 'AP', nome: 'AP' },
  { sigla: 'BA', nome: 'BA' },
  { sigla: 'CE', nome: 'CE' },
  { sigla: 'DF', nome: 'DF' },
  { sigla: 'ES', nome: 'ES' },
  { sigla: 'GO', nome: 'GO' },
  { sigla: 'MA', nome: 'MA' },
  { sigla: 'MG', nome: 'MG' },
  { sigla: 'MS', nome: 'MS' },
  { sigla: 'MT', nome: 'MT' },
  { sigla: 'PA', nome: 'PA' },
  { sigla: 'PB', nome: 'PB' },
  { sigla: 'PE', nome: 'PE' },
  { sigla: 'PI', nome: 'PI' },
  { sigla: 'PR', nome: 'PR' },
  { sigla: 'RJ', nome: 'RJ' },
  { sigla: 'RN', nome: 'RN' },
  { sigla: 'RO', nome: 'RO' },
  { sigla: 'RR', nome: 'RR' },
  { sigla: 'RS', nome: 'RS' },
  { sigla: 'SC', nome: 'RC' },
  { sigla: 'SE', nome: 'SE' },
  { sigla: 'SP', nome: 'SP' },
  { sigla: 'TO', nome: 'TO' }
];
